# Generated by Django 5.0.3 on 2024-06-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
